build.gradle, src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/BotDetectorPlugin.java, src/test/java/com/botdetector/BotDetectorPluginTest.java
I made the POST request run asynchronously. The submissionSet holds on to all unsuccessfully submitted names and gets cleared out after a 200 response code is received. This free ups the hashset h to collect fresh player names without getting bogged down in the main thread.
I also added some notification pop-ups to notify the user of how their submission attempts are going in the background.
=> Async POST + Notifications

src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/ui/BotDetectorPanel.java
This is to further avoid confusion with what the plugin actually does.
=> Change more instances of 'Reporting' to 'Uploading'

src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/model/CaseInsensitiveString.java, src/main/java/com/botdetector/ui/BotDetectorPanel.java
Names will now be sent in their original casing.
On the plugin side, when looking up our hashmaps, as long as we wrap the name in the CaseInsensitiveString class, it won't matter if the casing changes (mostly for panel prediction lookups).
=> Change player hashmaps to use a case insensitive string wrapper for the key

src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/ui/BotDetectorPanel.java
Potential bug: Double reporting if a prediction is set before a response from the server comes back for feedbacks and reports.
Real bug: Oh god all feedbacks were taken as +1...
Potential crash: Just making the hashmaps concurrent to avoid any potential crash with the panel threading.
Bonus: Add feedbacked/reported player name to chat message.
=> Fix a potential bug, a real bug and a potential crash

src/main/java/com/botdetector/ui/BotDetectorPanel.java
=> Apply WordUtils.capitalize to pred labels and right align % in breakdown

src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/BotDetectorPlugin.java
Removes the string box in config for the dev token, so you don't accidentally stream it or something.
`::bdGetToken` - Gets your token from your config and puts it in your clipboard.
`::bdSetToken` - Sets the token in your config to whatever's in your clipboard, as long as it's alphanumeric, underscores and hyphens and 12 to 32 characters long.
`::bdClearToken` Unsets the token in your config.
=> Hide dev tokens config, use commands and clipboard to set them

src/main/java/com/botdetector/ui/BotDetectorPanel.java
=> Add HTML tags to Player Name and Prediction Label fields to enable text wrapping

src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/BotDetectorPlugin.java
`Ints.constrainToRange` is commonly used in the Runelite project, see examples here:
https://github.com/runelite/runelite/search?q=ints.constrain
Upper limit I chose is 6h, or the game's default force logout timer.
=> Add upper range to auto send minutes and use guava to clamp

src/main/java/com/botdetector/BotDetectorPlugin.java
As runelite/runelite/pull/13224 got merged, Runelite version 1.7.7 will correctly order the inserted menu entries.
=> Restore previous insert menu entry method from HiscorePlugin

src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/BotDetectorPlugin.java
Adding a toggle to make the predict option standout more from the right-click menu as described in https://github.com/Bot-detector/bot-detector/issues/30.
=> Added toggle to highlight predict option

build.gradle
Non-hub candidates should have the `-DEV` string at the end.
When pulling for the hub, create a commit to remove this string, then PR that commit hash.
When the hub PR is accepted, increment this and put the `-DEV` back.
Normally I'd put `-SNAPSHOT`, but it's too long when the panel is in `Bold` mode.
=> Increment plugin version to 1.3.1-DEV

src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/model/PlayerSighting.java
Accidently closed the other one and it wouldn't let me re-open
Draft until we agree on how to send this and how it will be stored in the API
Example:
```
{
"reported": "Spoonami",
"region_id": 11571,
"x": 2936,
"y": 3281,
"z": 0,
"equipment": {
"AMULET": 19547,
"HANDS": 7462,
"TORSO": 11828,
"WEAPON": 20997,
"CAPE": 9757,
"LEGS": 11830,
"HEAD": 19645,
"BOOTS": 22954
},
"on_members_world": 1,
"on_pvp_world": 0,
"ts": 1620316965,
"reporter": "Cyborger1"
}
```
=> Add equipment item ids logging

src/main/java/com/botdetector/ui/BotDetectorPanel.java
Doesn't disappear on click anymore, just disables. Resets if there's an error sending and now uses our patented *Header-Label-With-Loading-Spinner™* technology.
=> Rework UIX for sending prediction feedback and flagging players

src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/model/PlayerSighting.java
Example:
```
{
"reported": "Sleepy Yoshi",
"region_id": 12598,
"x": 3168,
"y": 3491,
"z": 0,
"equipment": {
"LEGS": 12329,
"HANDS": 11133,
"HEAD": 4502,
"SHIELD": 3842,
"CAPE": 6568,
"WEAPON": 4170,
"TORSO": 13104,
"BOOTS": 23389,
"AMULET": 6585
},
"equipment_ge": 3697675,
"world_number": 304,
"on_members_world": 1,
"on_pvp_world": 0,
"ts": 1620594746,
"reporter": "Cyborger1"
},
```
From Equipment Inspector for reference:
=> Add total equipment GE value logging

build.gradle, config/checkstyle/checkstyle.xml, config/checkstyle/suppressions.xml
This will enforce that the checkstyle is respected before the plugin builds. The checks for `BotDetectorPluginTest.java` are disabled so it doesn't prevent building when people comment out the one line.
Once this is in, we can set up a GitHub workflow that will run the `build.gradle` file to make sure a PR's branch builds and complies with the checkstyle.
=> Add Runelite's checkstyle to project

src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/BotDetectorPlugin.java
I can't think of another `CC_OP_LOW_PRIORITY` called `Report` so I *think* this should be fine.
=> Add right-click predict to in-game report option

src/main/java/com/botdetector/ui/BotDetectorPanel.java
Essentially just moving the prediction ID check into the pred/flag if statement rather than being part of the condition, which allows the flagging check to happen even if the prediction check fails.
=> Allow flagging even if prediction does not return a player id

src/main/java/com/botdetector/ui/BotDetectorPanel.java
Just needs some persuasion with some `setMinimumSize()` and using a `BoxLayout` for the overarching layout manager. Apparently, `GridBoxLayout`-ception can break a few things.
=> Change panel code to not explode when text wraps

src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/BotDetectorPlugin.java
This option is disabled by default, but when enabled, the plugin will attempt to upload whatever it has pending when a ClientShutdown happens. This may cause the client to take a long time to close, although it seems there is a hard 10 seconds limit in [ClientUI.java](https://github.com/runelite/runelite/blob/e3840ca1fadef104ca473fb26029432b3063e855/runelite-client/src/main/java/net/runelite/client/ui/ClientUI.java#L630).
=> Add "Upload Names on Shutdown" option

src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/ui/PredictHighlightMode.java
The predict option will now stop highlighting when either the feedback or flagging panels have been interacted with, not just the flagging panel.
=> Extend dynamic Predict Highlight to account feedback

README.md, src/main/java/com/botdetector/BotDetectorConfig.java, src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/model/StatsCommandDetailLevel.java
Allows sharing plugin stats with other plugin users in-game. Works by calling the "Request Player Stats" API on the message's author.
=> Add '!bdstats' command

src/main/java/com/botdetector/BotDetectorPlugin.java
This should fix issues with people that have underscores and/or hyphens in their names. Ideally though, the API should *always* convert underscores and hyphens to spaces as they are all treated as the same in Jagex's systems. Case insensitivity seems to be handled correctly already, however.
Also this conflicts hard with #114, but I'll still leave it open for now as a draft.
=> Change name normalization in Discord Verification

src/main/java/com/botdetector/ui/BotDetectorPanel.java
Just makes the top part of the panel look a bit more balanced. The old margins were copied from the hiscore panel, but I don't think it's necessary for us to have the same.
Before:
After:
=> Remove some padding on top of the plugin panel

src/main/java/com/botdetector/ui/BotDetectorPanel.java
Fixes this text truncating by removed the left/right borders inside the button, which gives enough space for the text to display without the ellipses cutoff kicking in.
=> Fix truncated "Unsure" button text when the panel scrollbar is active

README.md, src/main/java/com/botdetector/BotDetectorConfig.java
Changes the config panel to be better organised. The Readme's FAQ section is also reordered to match the new config.
=> Rearrange config settings with sections

src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/ui/BotDetectorPanel.java
Should hopefully fix players starting on tutorial island and filter out invalid names for uploads as well.
=> Treat players with invalid names as logged out, don't process invalid names

src/main/java/com/botdetector/http/BotDetectorClient.java
If the json contains "error" for whatever reason, it'll have priority, but this will now work with the changes from switching to FastAPI on the other side.
=> Also check "detail" in API errors (FastAPI)

src/main/java/com/botdetector/ui/BotDetectorPanel.java
Sort % in reverse order still, but now also sort the key (bot label) for entries with the same %
=> Update comparator for displaying prediction breakdown

src/main/java/com/botdetector/BotDetectorPlugin.java
Should be effectively the same as the current implementation, but more robust. Recommended by Adam.
Left the immutable set in case we ever want to log world types other than standard. We could also just log any world type as long as we include it in the sighting. Food for thoughts.
=> Use RuneScapeProfileType to determine blocked worlds

src/main/java/com/botdetector/http/BotDetectorClient.java, src/main/java/com/botdetector/ui/BotDetectorPanel.java
Tweak to allow the feedback combobox to still be populated when Stats Too Low.
Instead of telling the API to not send a breakdown, the breakdown is now always requested, but hidden on the plugin side if confidence is null. The combobox can still be populated from the hidden breakdown.
=> Tweak null confidence case to allow populating feedback label list

src/main/java/com/botdetector/ui/BotDetectorPanel.java, src/main/java/com/botdetector/ui/Icons.java
Does not affect functionality, just a bit of tidying up. Originally used a supplier to ensure a new instance of the icon every time, but it seems this is unnecessary. Just make sure everything spins good, not a priority at all however.
=> Small refactor for Spinner Icons on the panel

src/main/java/com/botdetector/BotDetectorPlugin.java
Copying changes to Hiscore plugin:
https://github.com/runelite/runelite/blob/6e34fb4c9dcb57e0ffe67ccf26f1451eca0b8059/runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java#L150-L166
Draft for now until I make sure this doesn't break anything, shouldn't though as the original code was based on the same bit.
=> Change deprecated calls to WidgetID

src/main/java/com/botdetector/BotDetectorPlugin.java, src/main/java/com/botdetector/ui/BotDetectorPanel.java
First, swap over isActive variable logic over to panel side rather than try to keep the plugin class updated with that info.
Second, fix buttons not respecting background color when button is disabled. Flatlaf buttons function a bit differently than regular JButtons.
=> Flatlaf fixes
