Bot-detector/bot-detector

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorHeatMapOverlay.java
src/main/java/com/botdetector/BotDetectorPanel.java
src/main/java/com/botdetector/BotDetectorPlugin.java

A search bar has been added to the side panel.
There is now an option to disable notifications.
Names are uploaded upon logout. Users wanting to send names every X game ticks instead have that option also.
The calls to the API are now formatted in JSON to include location information, as well as the player sending the reports.

Panel Updates, Changes to API Calls

---

src/main/java/com/botdetector/BotDetectorPanel.java
src/main/java/com/botdetector/BotDetectorPlugin.java

Removed imports that are no longer being used.

Removed Unneeded Imports

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorHTTP.java
src/main/java/com/botdetector/BotDetectorPanel.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/PlayerStats.java

Side panel now gives more information on historical user participation data.
I moved all of the OkClient methods to their own class.

Major refactoring of the code base. Updated Side Panel

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java

Mostly remove the columns (`:`) and use `@Range` and `@Units` for the time field.

Clean up config labels

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorHTTP.java
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/model/Prediction.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java
src/main/java/com/botdetector/ui/GameOverlays/BotDetectorHeatMapOverlay.java
src/main/java/com/botdetector/ui/GameOverlays/BotDetectorTileOverlay.java
src/main/java/com/botdetector/ui/Icons.java

Uses the checkstyle conventions available on [Runelite's github](https://github.com/runelite/runelite/wiki/Code-Conventions).
While I did change a few very slight things, I refrained from refactoring anything substantial in this PR.

Apply Runelite Checkstyle to all classes

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorHTTP.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java
src/main/java/com/botdetector/ui/GameOverlays/BotDetectorHeatMapOverlay.java

Still not much refactoring going on, just cleaning up things that would cause compiler warnings.
Also prefer early `return` in some places.

Cleanup code to reduce warning counts

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java
src/main/java/com/botdetector/ui/PanelFontType.java

I also moved the tooltip for the feedback panel from the header to the buttons

Add option to switch font size on prediction panel

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/model/PlayerSighting.java

Added so it's already there for when we want to do stuff with this on the API side

Add PVP world identifier to sightings

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Adds commas between thousands:

Use Runelite's QuantityFormatter in the reporting statistics panel

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Swap Probable/Confirmed bans on the plugin panel

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/model/CaseInsensitiveString.java
src/main/java/com/botdetector/model/PlayerSighting.java
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/model/Prediction.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java
src/main/java/com/botdetector/ui/Icons.java
src/main/java/com/botdetector/ui/PanelFontType.java

It's a thing they do in the Runelite source code, I also do it in my plugins

Add License headers to every source file

---

build.gradle

Uncomment these and use the shadowjar build step in gradle to create the shadow jar

Add shadowjar comments

---

src/main/java/com/botdetector/model/PlayerSighting.java

Thankfully the data was the right data :)

Just change these var names cause they were wrong

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Also some more input validation
And yes I brought back the old sanitize method, sorry for questioning you Seltz

Add custom prediction errors

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

Marking as draft until some changes on the API side
Also `checkPostSuccess` probably doesn't need the map check as long as 200 OKs are only ever returned when everything worked 100%. Return 400 if something went wrong then do the error map check there to get the error string.
EDIT: I think this may be good to un-draft actually

Check for error key in returned map, surround functions in try/finally

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/model/AuthToken.java
src/main/java/com/botdetector/model/AuthTokenPermission.java
src/main/java/com/botdetector/model/AuthTokenType.java

Draft until @Ferrariic gets in touch to redo the tokens or something?

Rework Auth Tokens

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java

Just merging this into master and cleaning up a bit

Dev merge and tweak

---

src/main/java/com/botdetector/BotDetectorPlugin.java

Ensure the player option is always removed

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/model/PlayerStatsType.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

This currently only works on `/dev/`

Add player stats breakdown to panel

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

Just some more internal housekeeping on the plugin side. Variables sent/received through the API are unchanged.

Rename most variables relating to reports to uploads/flags

---

src/main/java/com/botdetector/BotDetectorPlugin.java

More specifically, refresh occurs when going from states LOGGED_IN -> LOADING -> LOGGED_IN, the intent is to refresh player sightings in situations where the players never leave the client cache, such as loading into instances or different areas with the players sticking through the load.

Trigger sightings refresh after loading screen

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Adjust padding on the player stats tabs

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

Add breakdown to current uploads field

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Center player stats tab labels

---

src/main/java/com/botdetector/BotDetectorPlugin.java

Don't account for instances when not in an instance

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java
src/main/java/com/botdetector/ui/components/JLimitedTextArea.java

Edit: Just putting this here, the reason I chose to make empty strings be sent as `null` is so the field doesn't get added to the JSON if there was no feedback text included with the feedback.

Add textbox to feedback panel

---

src/main/java/com/botdetector/BotDetectorPlugin.java

See https://github.com/runelite/runelite/commit/1c75a97df543c7286d6000b928e6ef1917c0bae6#

Add predict option to clan chat / guest clan chat

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/events/BotDetectorPanelActivated.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/http/UnauthorizedTokenException.java
src/main/java/com/botdetector/model/AuthToken.java
src/main/java/com/botdetector/model/AuthTokenPermission.java
src/main/java/com/botdetector/model/AuthTokenType.java
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java
src/main/java/com/botdetector/ui/PredictHighlightMode.java
src/main/java/com/botdetector/ui/components/JLimitedTextArea.java

Add Javadoc to most things

---

src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/BotDetectorPlugin.java

Toggle command is `::bdToggleShowDiscordVerificationErrors` (alias available as `::bdToggleDVE`),

Add toggle to hide discord verification errors and show the actual error in chat

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Hopefully this helps with people sending incorrect feedbacks.

Update prediction feedback tooltip text

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Hopefully makes it clearer that the negative option is *actually* negative.
From:
To:

Change prediction feedback button texts

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/model/PlayerSighting.java

Fix equipment ge value overflow

---

README.md

This took a while haha, please give this a thorough read-through!

Redo the README with updated information

---

src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/model/Prediction.java

There may never be a time where this change makes a difference, but you can never be too careful.

Change some ints to longs just in case these ever get high enough

---

README.md
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

Add prediction feedback tally field to player stats

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/model/FeedbackPredictionLabel.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java
src/main/java/com/botdetector/ui/components/ComboBoxSelfTextTooltipListRenderer.java

Draft for now until the API can take in the new values.
@ThorntonMatthewD we should probably meet up in the Discord to review this one it's a big one lol.

Rework prediction feedback with dropdown

---

src/main/java/com/botdetector/BotDetectorPlugin.java

Change WorldTypes to new names in RL 1.7.21

---

build.gradle
src/main/java/com/botdetector/BotDetectorPlugin.java

As requested by abex on the runelite discord

Change how gradle builds the version file

---

src/main/java/com/botdetector/http/BotDetectorClient.java

Also fixes deprecation on RuneLiteAPI.CLIENT. I'll update the build.gradle to 1.3.7.2 and push this to the hub whenever this is pulled.
This change should help us identify people who have incorrect system clocks on the API side and adjust their sent data accordingly.

Add `Request-Epoch` to all request headers

---

build.gradle
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/model/PlayerSighting.java
src/main/java/com/botdetector/model/PlayerStats.java
src/main/java/com/botdetector/model/Prediction.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

Draft for now, these are the tentative changes for adapting the plugin to the new API (https://www.osrsbotdetector.com/dev/docs#/).

Convert to New API

---

build.gradle

+ Changes runeLiteVersion to 'latest.release'. This improves development qol.

Changes def runeLiteVersion -> 'latest.release'

---

README.md
src/main/java/com/botdetector/BotDetectorConfig.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/model/Prediction.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

Defaults to `false` in the config

Add option for Breakdown on Special Cases

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/http/BotDetectorClient.java
src/main/java/com/botdetector/http/ValidationException.java

My sanity is rapidly dwindling regarding these bad region IDs :)

Add handling for invalid data 422, more checks against bad region IDs

---

src/main/java/com/botdetector/ui/BotDetectorPanel.java

Add tooltips on flag/feedback panel headers on error

---

src/main/java/com/botdetector/http/BotDetectorClient.java

When I don't know how to parse the error JSON, just log it whole loool LET'S GOOOOOO

Better logging for unparsable error messages

---

src/main/java/com/botdetector/BotDetectorPlugin.java
src/main/java/com/botdetector/ui/BotDetectorPanel.java

This patches the plugin to be compatible with the RuneLite FlatLaf changes (runelite/runelite#17284), that was made live recently, resulting in the plugin not working anymore.

Fix FlatLaf Compatability
